<?php
echo "HTTP_CF_CONNECTING_IP:".$_SERVER['HTTP_CF_CONNECTING_IP'];
echo "<br>HTTP_CLIENT_IP:".$_SERVER['HTTP_CLIENT_IP'];
echo "<br>REMOTE_ADDR:".$_SERVER['REMOTE_ADDR'];
echo "<br>HTTP_X_FORWARDED_FOR:".$_SERVER['HTTP_X_FORWARDED_FOR'];
echo "<br>HTTP_X_REAL_IP:".$_SERVER['HTTP_X_REAL_IP'];
?>